# Generated by Django 3.2 on 2021-05-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210506_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='feature_1_content',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='feature_2_content',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='feature_3_content',
            field=models.TextField(blank=True, max_length=120),
        ),
    ]
