# Generated by Django 3.2 on 2021-05-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_main_title', models.CharField(max_length=120)),
                ('card_main_content', models.TextField(blank=True, max_length=500)),
                ('card_left_title', models.CharField(max_length=120)),
                ('card_left_content', models.TextField(blank=True, max_length=500)),
                ('card_right_title', models.CharField(max_length=120)),
                ('card_right_content', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'About Page',
            },
        ),
        migrations.AddField(
            model_name='productdetail',
            name='feature_1_content',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='feature_1_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='feature_2_content',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='feature_2_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='feature_3_content',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='feature_3_title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
