# Generated by Django 3.2.3 on 2021-05-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210522_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='audio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='communications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='connections',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_the_box',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_support',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.TextField(blank=True),
        ),
    ]
