# Generated by Django 3.2.3 on 2021-05-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210514_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_img',
            field=models.ImageField(blank=True, upload_to='products/images/'),
        ),
    ]
